FROM golang:1.20.3-alpine3.17 AS builder

RUN mkdir -p /build
WORKDIR /build

COPY go.mod .
COPY go.sum .
RUN go mod vendor
COPY . .
RUN CGO_ENABLED=0 env GOOS=linux GOARCH=amd64 go build -o kubeins main.go

ENTRYPOINT ["kubeins"]
CMD [""]
